package form;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class ConversorGenerico extends javax.swing.JFrame {

    
    public boolean option1 = false; 
    public boolean option2 = true;
    int selectedIndex;
    double conversion1;
    double conversion2;
    
   List<Conversor> conversores;
   
   
    public ConversorGenerico() {
        initComponents();
        
        //centrar ventana
        setLocationRelativeTo(null);
        //

        //titulo de ventana
        this.setTitle("Conversor");
        //
        
        //icono de ventana
        setIconImage(new ImageIcon(getClass().getResource("/img/icon.png")).getImage());
        //
        
     
        //LLenar el combo
        conversores = new ArrayList<>();
        conversores.add(new CentimetrosCentimetroPulgada());
        conversores.add(new MetrosMetrosKilometros());
        conversores.add(new HoraHoraMinuto());
        conversores.add(new CelsiusCelsiusKelvin());
        conversores.add(new ByteByteKilobyte());
        
        for (Conversor conversor : conversores) {
            
            ConversoresComboBox.addItem(conversor.toString());
            
        }
        
        
        
        setLabels();
        
    }

    
    
    
    private void setLabels() {
        selectedIndex = ConversoresComboBox.getSelectedIndex();
        valor1Label.setText(conversores.get(selectedIndex).getLabelValor1());
        valor2Label.setText(conversores.get(selectedIndex).getLabelValor2());   
    }//asi como setea los labels se puede crear una clase que cambia la logica de las cuentas segun el selected index del comboBox

    private void convertir(){
         // Evento del boton
        System.out.println("Transform");
        
        if(option1){
            System.out.println("Transform option2 a option1");
            
            String pulgValue = inputPulgadas.getText().replace(",", ".");
            
              pulgValue = pulgValue.replace("\n", "");
                   
            Double pulgDouble;
            
            
            try {
            
                pulgDouble = Double.valueOf(pulgValue);    
               
                        
            } catch (NumberFormatException e) {
            
                //mostrar error de excepciones
            
                JOptionPane.showMessageDialog(this, "No se pudo procesar la informacion.", "Error de lectura", JOptionPane.ERROR_MESSAGE);
            
             return;
            }
        
        //centAPulgada, cent /2.54
        Double centDouble = conversores.get(selectedIndex).convertirAValor2(pulgDouble);//pulgDouble * 2.54; //igualar a metodo conversor.centimetrospulgada.convertirAValor2();
        inputCentimetros.setText(String.format("%.5f",centDouble));
        
        }
        
        
        
        
        if(option2){
            System.out.println("Transform option1 a option2");
            
            String centValue = inputCentimetros.getText().replace(",", ".");
            
              centValue = centValue.replace("\n", "");
                 
                 
        Double centDouble;
        try {
            
            centDouble = Double.valueOf(centValue);    
            
        } catch (NumberFormatException e) {
            
            //mostrar error de excepciones
            
            JOptionPane.showMessageDialog(this, "No se pudo procesar la informacion.", "Error de lectura", JOptionPane.ERROR_MESSAGE);
            
            
            
            return;
        }
        
        //centAPulgada, cent /2.54
        Double pulgDouble = conversores.get(selectedIndex).convertirAValor1(centDouble);// centDouble / 2.54;//igualar a metodo conversor.centimetrospulgada.convertirAValor1();
        inputPulgadas.setText(String.format("%.5f",pulgDouble));
            
        }
        
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor1Label = new javax.swing.JLabel();
        inputCentimetros = new javax.swing.JTextField();
        valor2Label = new javax.swing.JLabel();
        inputPulgadas = new javax.swing.JTextField();
        ConvertirBtn = new javax.swing.JButton();
        ConversoresComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        valor1Label.setText("valor1");

        inputCentimetros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCentimetrosFocusLost(evt);
            }
        });
        inputCentimetros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCentimetrosKeyReleased(evt);
            }
        });

        valor2Label.setText("valor2");

        inputPulgadas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPulgadasFocusLost(evt);
            }
        });
        inputPulgadas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPulgadasKeyPressed(evt);
            }
        });

        ConvertirBtn.setText("Convertir");
        ConvertirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirBtnActionPerformed(evt);
            }
        });

        ConversoresComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ConversoresComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valor1Label)
                            .addComponent(valor2Label))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCentimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConversoresComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConvertirBtn)
                                .addGap(22, 22, 22))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valor1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCentimetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConvertirBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConversoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirBtnActionPerformed
       convertir();
    }//GEN-LAST:event_ConvertirBtnActionPerformed

    private void inputCentimetrosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCentimetrosFocusLost
        // TODO add your handling code here:
        System.out.println("focus lost option1");
        option1 = false;
        option2 = true;
    }//GEN-LAST:event_inputCentimetrosFocusLost

    private void inputPulgadasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPulgadasFocusLost
        // TODO add your handling code here:
        System.out.println("focus lost option2");
        option2 = false;
        option1 = true;
    }//GEN-LAST:event_inputPulgadasFocusLost

    private void ConversoresComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ConversoresComboBoxItemStateChanged
        
        //cambia todo depende de lo que se elija en el combobox
        
        setLabels();
         
    }//GEN-LAST:event_ConversoresComboBoxItemStateChanged

    private void inputCentimetrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCentimetrosKeyReleased
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("enter option1 a option2");
            convertir();
        }
        
        
    }//GEN-LAST:event_inputCentimetrosKeyReleased

    private void inputPulgadasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPulgadasKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("enter option2 a option1");
            convertir();
        }
    }//GEN-LAST:event_inputPulgadasKeyPressed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ConversoresComboBox;
    private javax.swing.JButton ConvertirBtn;
    private javax.swing.JTextField inputCentimetros;
    private javax.swing.JTextField inputPulgadas;
    private javax.swing.JLabel valor1Label;
    private javax.swing.JLabel valor2Label;
    // End of variables declaration//GEN-END:variables
}



// press enter to action
//
// 5 tipos de conversiones